### ISSUE TITLE
We need a x86 build of the Tor binary for Android

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Tor_Onion_Proxy_Library#35]
Right now nobody can use any of the decent Android emulators because they all depend on x86 and we don't have an x86 build of the Android binary.

**Comment by n8fr8** [comment]
We now provide a standalone project, with public gradle dependency, for building the tor binary. Hoping to re-energize your project here, and get that included: https://github.com/n8fr8/tor-android

**Comment by yaronyg** [comment]
That is awesome! Seriously. Unfortunately right now my new job (I started working for Cosmos DB in Azure) has me so drowning it's going to be awhile before I do anything other than work and sleep.

**Comment by yaronyg** [comment]
That is awesome! Thank you!

**Comment by n8fr8** [comment]
👍
