### ISSUE TITLE
Problem Installing Gradle

### ISSUE THREAD

**Issue by PanagiotisDrakatos** [thaliproject/Tor_Onion_Proxy_Library#38]
i am putting the above dependencies
compile 'com.msopentech.thali:ThaliOnionProxyJava:0.0.2'
compile 'com.msopentech.thali:BriarJtorctl:0.0.2'
 in the gradle file but i get this error can you help me please to fix this

Could not resolve all dependencies for configuration ':compile'.

> Could not find com.msopentech.thali:ThaliOnionProxyJava:0.0.2.
>   Searched in the following locations:
>       file:/C:/Users/User/.m2/repository/com/msopentech/thali/ThaliOnionProxyJava/0.0.2/ThaliOnionProxyJava-0.0.2.pom
>       file:/C:/Users/User/.m2/repository/com/msopentech/thali/ThaliOnionProxyJava/0.0.2/ThaliOnionProxyJava-0.0.2.jar
>   Required by:
>       :Project_Name:unspecified

**Comment by JesusMcCloud** [comment]
AFAIK this project is not really maintained anymore. You are Welcome to try [this fork](https://github.com/ManfredKarrer/jtorproxy) which includes some fixes.

**Comment by stathmarxis** [comment]
thank very much !!!

**Comment by PanagiotisDrakatos** [comment]
i am stil having the same problem with dependencies is there  any possibility to fix this

**Comment by JesusMcCloud** [comment]
Have you installed everything into your local maven repository?
In case you are using the forked version: Did you adapt the dependency names? (They changed)
At least, that's what the original error points to...
You not only have to `mvn compile` and/or `mvn package`, but also `mvn install` everything in order for it to be discoverable as a dependency in other projects.
