### ISSUE TITLE
update tor-android-binary available (0.3.3.5)

### ISSUE THREAD

**Issue by n8fr8** [thaliproject/Tor_Onion_Proxy_Library#46]
I've pushed an update here: https://github.com/n8fr8/tor-android/commit/63723e06ef4c981a5c94bbd16ed05e2d6713c62f

The new gradle dependency version is: 0.3.3.5-rc-3

I have also modified how the binaries are packaged (now they are stored as faux .so files), and updated the TorResourceInstaller logic, to handle all the platform variations. If you are using that class, from the library, then all should be fine.

Lastly, the library now includes armeabi, armeabi-v7a, and x86 binaries. Thinking about adding 64-bit builds soon as well. Any app using this library, should doing split APK builds or app bundles to keep the total APK file size down.

**Comment by sisbell** [comment]
Looks like latest now is 0.3.5.6-rc. There is one compile time breakage. TorResourceInstaller.streamToFile is private in latest version, which is easy to fix up.
