### ISSUE TITLE
Upgrade for Android Q

### ISSUE THREAD

**Issue by sisbell** [thaliproject/Tor_Onion_Proxy_Library#85]
It looks like Android Q will block executing native code from the /data/data writeable space. We can configure to run from the read-only app private space but this will require changes to the way we handle setup. 

Currently, by default, we use a simple flat directory, with the executable and config files in the same location. We can't do this anymore since we can't write the config files to the same directory as the executable.

This should only affect the android module, not universal.

https://www.reddit.com/r/androiddev/comments/b2inbu/psa_android_q_blocks_executing_binaries_in_your/

**Comment by eighthave** [comment]
The other annoyance is that the executable files have be named at least with _.so_ on the end, perhaps even also with _lib_ on the beginning.  Seems like a better solution would be to get the Android _TorService_ to link against tor as a proper shared library.  This is working well on iOS now.

**Comment by n8fr8** [comment]
Agreed we should move to actual shared libraries, but for now...

We have an initial release out for testing that hopefully addresses the Android Q issue:

​https://github.com/n8fr8/tor-android/releases/tag/tor-android-binary-tor-0.3.5.8-rc

and a build of Orbot, as well, based on this:
​https://github.com/n8fr8/orbot/releases/tag/16.0.6-BETA-1-tor-0.3.5.8

There is a new gradle dependency published as well:
org.torproject:tor-android-binary:0.3.5.8-rc
